services:
  worker:
    build: { context: ., dockerfile: Dockerfile.worker }
    labels:
      - "role=worker"

  scaler:
    build: { context: ., dockerfile: Dockerfile.scaler }
    depends_on: [worker]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./targets:/etc/prometheus/targets

  controller:
    build: { context: ., dockerfile: Dockerfile.controller }
    depends_on: [worker, scaler]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./targets:/etc/prometheus/targets

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./targets:/etc/prometheus/targets
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on: [prometheus]